-- 🔧 STUDYCONNECT DATABASE SCHEMA PATCH (V2)
-- Run this in your Supabase SQL Editor to make sure all tables and columns match the application code.

-- 1. Patch the "posts" table
ALTER TABLE posts ADD COLUMN IF NOT EXISTS tag VARCHAR(255) DEFAULT NULL;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS likes JSONB DEFAULT '[]'::jsonb;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS group_id BIGINT DEFAULT NULL;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN DEFAULT FALSE;

-- Add foreign key constraint for group_id if not already present
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'fk_posts_group'
    ) THEN
        ALTER TABLE posts 
        ADD CONSTRAINT fk_posts_group 
        FOREIGN KEY (group_id) REFERENCES study_groups(id) ON DELETE CASCADE;
    END IF;
END $$;


-- 2. Patch the "messages" table
ALTER TABLE messages ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN DEFAULT FALSE;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS reply_to JSONB DEFAULT NULL;


-- 3. Create the "friendships" table if it doesn't exist
CREATE TABLE IF NOT EXISTS friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    to_user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(50) DEFAULT 'pending', -- 'pending', 'accepted', 'declined'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    accepted_at TIMESTAMP WITH TIME ZONE,
    UNIQUE (from_user_id, to_user_id)
);

-- Enable RLS for friendships
ALTER TABLE friendships ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read friendships" ON friendships;
CREATE POLICY "Allow public read friendships" ON friendships FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow insert friendships" ON friendships;
CREATE POLICY "Allow insert friendships" ON friendships FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow update friendships" ON friendships;
CREATE POLICY "Allow update friendships" ON friendships FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow delete friendships" ON friendships;
CREATE POLICY "Allow delete friendships" ON friendships FOR DELETE USING (true);


-- 4. Create the "files" table if it doesn't exist
CREATE TABLE IF NOT EXISTS files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT REFERENCES study_groups(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    file_type VARCHAR(100) NOT NULL,
    file_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS for files
ALTER TABLE files ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read files" ON files;
CREATE POLICY "Allow public read files" ON files FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow insert files" ON files;
CREATE POLICY "Allow insert files" ON files FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow delete files" ON files;
CREATE POLICY "Allow delete files" ON files FOR DELETE USING (true);


-- 5. Create the "schedules" table if it doesn't exist
CREATE TABLE IF NOT EXISTS schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT REFERENCES study_groups(id) ON DELETE CASCADE,
    topic VARCHAR(255) NOT NULL,
    date_time TIMESTAMP WITH TIME ZONE NOT NULL,
    location VARCHAR(255) DEFAULT 'Online',
    description TEXT DEFAULT NULL,
    creator_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS for schedules
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read schedules" ON schedules;
CREATE POLICY "Allow public read schedules" ON schedules FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow insert schedules" ON schedules;
CREATE POLICY "Allow insert schedules" ON schedules FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow update schedules" ON schedules;
CREATE POLICY "Allow update schedules" ON schedules FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow delete schedules" ON schedules;
CREATE POLICY "Allow delete schedules" ON schedules FOR DELETE USING (true);


-- 6. Create the "deadlines" table if it doesn't exist
CREATE TABLE IF NOT EXISTS deadlines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT REFERENCES study_groups(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    due_date TIMESTAMP WITH TIME ZONE NOT NULL,
    description TEXT DEFAULT NULL,
    creator_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    assignee_id BIGINT REFERENCES users(id) ON DELETE CASCADE DEFAULT NULL,
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS for deadlines
ALTER TABLE deadlines ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read deadlines" ON deadlines;
CREATE POLICY "Allow public read deadlines" ON deadlines FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow insert deadlines" ON deadlines;
CREATE POLICY "Allow insert deadlines" ON deadlines FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow update deadlines" ON deadlines;
CREATE POLICY "Allow update deadlines" ON deadlines FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow delete deadlines" ON deadlines;
CREATE POLICY "Allow delete deadlines" ON deadlines FOR DELETE USING (true);

-- Grant privileges to sequence & tables
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON friendships TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON files TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON schedules TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON deadlines TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON posts TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON messages TO anon, authenticated;
