-- Migration 09: Add major column to study_groups & create subjects_by_major table
-- Run this in Supabase SQL Editor

-- 1. Add major column to study_groups (ngành học của nhóm)
ALTER TABLE study_groups ADD COLUMN IF NOT EXISTS major VARCHAR(255) DEFAULT NULL;

-- 2. Create subjects_by_major table (lưu danh sách môn học theo từng ngành học)
CREATE TABLE IF NOT EXISTS subjects_by_major (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  major VARCHAR(255) NOT NULL,
  subject_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (major, subject_name)
);

-- 3. Enable Row Level Security
ALTER TABLE subjects_by_major ENABLE ROW LEVEL SECURITY;

-- 4. Policies
DROP POLICY IF EXISTS "Allow select subjects_by_major" ON subjects_by_major;
CREATE POLICY "Allow select subjects_by_major" ON subjects_by_major
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow insert subjects_by_major" ON subjects_by_major;
CREATE POLICY "Allow insert subjects_by_major" ON subjects_by_major
  FOR INSERT WITH CHECK (true);

-- 5. Grants
GRANT SELECT, INSERT ON subjects_by_major TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- 6. Seed dữ liệu môn học ban đầu theo ngành học
INSERT INTO subjects_by_major (major, subject_name) VALUES
  -- Công nghệ thông tin
  ('Công nghệ thông tin', 'Toán cao cấp'),
  ('Công nghệ thông tin', 'Lập trình Web'),
  ('Công nghệ thông tin', 'Cơ sở dữ liệu'),
  ('Công nghệ thông tin', 'Mạng máy tính'),
  ('Công nghệ thông tin', 'Trí tuệ nhân tạo'),
  ('Công nghệ thông tin', 'Cấu trúc dữ liệu và giải thuật'),
  ('Công nghệ thông tin', 'Hệ điều hành'),
  -- Kỹ thuật phần mềm
  ('Kỹ thuật phần mềm', 'Toán cao cấp'),
  ('Kỹ thuật phần mềm', 'Lập trình Web'),
  ('Kỹ thuật phần mềm', 'Cơ sở dữ liệu'),
  ('Kỹ thuật phần mềm', 'Kỹ nghệ phần mềm'),
  ('Kỹ thuật phần mềm', 'Kiểm thử phần mềm'),
  ('Kỹ thuật phần mềm', 'Cấu trúc dữ liệu và giải thuật'),
  -- Khoa học máy tính
  ('Khoa học máy tính', 'Toán cao cấp'),
  ('Khoa học máy tính', 'Trí tuệ nhân tạo'),
  ('Khoa học máy tính', 'Cấu trúc dữ liệu và giải thuật'),
  ('Khoa học máy tính', 'Học máy'),
  ('Khoa học máy tính', 'Xử lý ngôn ngữ tự nhiên'),
  -- An toàn thông tin
  ('An toàn thông tin', 'Mật mã học'),
  ('An toàn thông tin', 'An ninh mạng'),
  ('An toàn thông tin', 'Lập trình Web'),
  ('An toàn thông tin', 'Hệ điều hành'),
  -- Hệ thống thông tin
  ('Hệ thống thông tin', 'Cơ sở dữ liệu'),
  ('Hệ thống thông tin', 'Phân tích hệ thống'),
  ('Hệ thống thông tin', 'Quản trị dự án'),
  -- Trí tuệ nhân tạo
  ('Trí tuệ nhân tạo', 'Học máy'),
  ('Trí tuệ nhân tạo', 'Xử lý ngôn ngữ tự nhiên'),
  ('Trí tuệ nhân tạo', 'Thị giác máy tính'),
  ('Trí tuệ nhân tạo', 'Toán cao cấp'),
  -- Quản trị kinh doanh
  ('Quản trị kinh doanh', 'Kinh tế vĩ mô'),
  ('Quản trị kinh doanh', 'Kinh tế vi mô'),
  ('Quản trị kinh doanh', 'Nguyên lý kế toán'),
  ('Quản trị kinh doanh', 'Quản trị học'),
  ('Quản trị kinh doanh', 'Marketing căn bản'),
  -- Kinh doanh quốc tế
  ('Kinh doanh quốc tế', 'Kinh tế quốc tế'),
  ('Kinh doanh quốc tế', 'Marketing quốc tế'),
  ('Kinh doanh quốc tế', 'Luật thương mại quốc tế'),
  -- Kế toán / Kiểm toán
  ('Kế toán / Kiểm toán', 'Nguyên lý kế toán'),
  ('Kế toán / Kiểm toán', 'Kế toán tài chính'),
  ('Kế toán / Kiểm toán', 'Kiểm toán'),
  ('Kế toán / Kiểm toán', 'Tài chính doanh nghiệp'),
  -- Tài chính - Ngân hàng
  ('Tài chính - Ngân hàng', 'Tài chính doanh nghiệp'),
  ('Tài chính - Ngân hàng', 'Ngân hàng thương mại'),
  ('Tài chính - Ngân hàng', 'Thị trường chứng khoán'),
  -- Marketing
  ('Marketing', 'Marketing căn bản'),
  ('Marketing', 'Marketing kỹ thuật số'),
  ('Marketing', 'Nghiên cứu thị trường'),
  ('Marketing', 'Quản trị thương hiệu'),
  -- Ngôn ngữ Anh
  ('Ngôn ngữ Anh', 'Nghe nói chuyên sâu'),
  ('Ngôn ngữ Anh', 'Đọc viết học thuật'),
  ('Ngôn ngữ Anh', 'Biên dịch'),
  ('Ngôn ngữ Anh', 'Phiên dịch'),
  -- Ngôn ngữ Trung Quốc
  ('Ngôn ngữ Trung Quốc', 'Tiếng Trung cơ bản'),
  ('Ngôn ngữ Trung Quốc', 'Ngữ pháp tiếng Trung'),
  ('Ngôn ngữ Trung Quốc', 'Biên phiên dịch Trung - Việt'),
  -- Thiết kế đồ họa
  ('Thiết kế đồ họa', 'Nguyên lý thiết kế'),
  ('Thiết kế đồ họa', 'Thiết kế UI/UX'),
  ('Thiết kế đồ họa', 'Nhiếp ảnh'),
  -- Logistics
  ('Logistics và Quản lý chuỗi cung ứng', 'Quản lý chuỗi cung ứng'),
  ('Logistics và Quản lý chuỗi cung ứng', 'Vận tải quốc tế'),
  ('Logistics và Quản lý chuỗi cung ứng', 'Quản trị kho hàng'),
  -- Công nghệ kỹ thuật điện
  ('Công nghệ kỹ thuật điện, điện tử', 'Mạch điện'),
  ('Công nghệ kỹ thuật điện, điện tử', 'Điện tử tương tự'),
  ('Công nghệ kỹ thuật điện, điện tử', 'Vi điều khiển'),
  ('Công nghệ kỹ thuật điện, điện tử', 'Kỹ thuật số')
ON CONFLICT (major, subject_name) DO NOTHING;
